const data={name:'Akash',date:'September 9, 2026',traits:[['✦','The Energy','Somehow you bring energy into even the most random moments.'],['☀','The Laughs','The best moments usually become funny stories later.'],['◎','The Friendship','The kind of friendship that makes ordinary days better.'],['↗','The Ambition','Keep chasing the things that make you excited about tomorrow.'],['◈','The Vibe','Effortlessly yourself. That is the whole point.'],['✧','The Memories','Here is to making a lot more of them this year.']],memories:[{date:'A day to remember',title:'That random day',description:"One of those moments we'll always remember."},{date:'Somewhere between plans',title:'The good times',description:'The kind of day that did not need a plan.'},{date:'Still one of the favourites',title:'Another memory',description:'Add a real photo later and keep this one forever.'}],wishes:[['A friend','Keep smiling, keep growing, and keep being the person everyone enjoys having around.'],['Someone who cares','May this year bring you good people, good surprises, and plenty of reasons to laugh.'],['Your future self','You have a lot ahead of you. Go make it a year worth remembering.']]};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),traits=$('#traits'),memories=$('#memories'),wishes=$('#wishes');
data.traits.forEach(([icon,title,description])=>{const el=document.createElement('article');el.className='trait';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-expanded','false');el.innerHTML=`<div class="trait-icon">${icon}</div><h3>${title}</h3><p>${description}</p>`;const toggle=()=>{const open=el.classList.toggle('open');el.setAttribute('aria-expanded',String(open));effect('tap')};el.onclick=toggle;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}};traits.appendChild(el)});
data.memories.forEach((m,i)=>{const el=document.createElement('article');el.className='memory';el.tabIndex=0;el.innerHTML=`<div class="memory-visual">${i+1} · a moment</div><div class="memory-info"><small>${m.date}</small><h3>${m.title}</h3><p>${m.description}</p></div>`;const open=()=>{effect('tap');openModal(m)};el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};memories.appendChild(el)});
data.wishes.forEach(([from,msg])=>{const el=document.createElement('article');el.className='wish';el.innerHTML=`<p>“${msg}”</p><small>— ${from}</small>`;el.onclick=()=>effect('tap');wishes.appendChild(el)});
function openModal(m){$('#modalDate').textContent=m.date;$('#modalTitle').textContent=m.title;$('#modalDescription').textContent=m.description;const visual=$('#modalVisual');visual.className='modal-visual';visual.textContent='A memory waiting for its photo ✦';if(m.image){visual.style.backgroundImage=`url('${m.image}')`;visual.textContent=''}$('#modal').hidden=false;$('#modalClose').focus()}
function closeModal(){effect('close');$('#modal').hidden=true}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()});
function celebrate(){const box=$('#confetti');for(let i=0;i<90;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left='50%';p.style.top='45%';p.style.setProperty('--x',`${(Math.random()-.5)*110}vw`);p.style.setProperty('--y',`${(Math.random()-.3)*110}vh`);p.style.transform=`rotate(${Math.random()*360}deg)`;p.style.background=`hsl(${Math.random()*55+325} 70% ${65+Math.random()*20}%)`;box.appendChild(p)}setTimeout(()=>box.replaceChildren(),2200)}
let audioCtx=null,master=null,playing=false,musicTimer=null;const melody=[261.63,329.63,392,523.25,392,329.63,293.66,349.23,440,523.25,440,349.23,261.63,329.63,392,493.88];
function ensureAudio(){if(!audioCtx){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;audioCtx=new Ctx();master=audioCtx.createGain();master.gain.value=.28;master.connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume();return true}
function tone(freq,duration=.34,delay=0,type='sine',gain=.08){if(!ensureAudio())return;const now=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.018);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(master);o.start(now);o.stop(now+duration+.03)}
function playBirthdayPhrase(){for(let i=0;i<melody.length;i++)tone(melody[i],.3,i*.3,'sine',.085);tone(melody[0]/2,4.7,0,'triangle',.028)}
function startMusic(){if(!ensureAudio()||playing)return;playing=true;playBirthdayPhrase();musicTimer=setInterval(()=>{if(playing)playBirthdayPhrase()},melody.length*300);$('#musicToggle').hidden=false;$('#musicToggle').textContent='♫';$('#musicToggle').setAttribute('aria-label','Pause birthday music');$('#musicEnable').textContent='♫ Birthday Music On'}
function stopMusic(){playing=false;clearInterval(musicTimer);musicTimer=null;$('#musicToggle').textContent='♪';$('#musicToggle').setAttribute('aria-label','Play birthday music');$('#musicEnable').textContent='♬ Play Birthday Music'}
function effect(kind){if(kind==='open'){tone(392,.14,0,'sine',.14);tone(523.25,.18,.08,'sine',.13);tone(659.25,.28,.17,'sine',.11)}else if(kind==='tap'){tone(880,.07,0,'sine',.055)}else if(kind==='close'){tone(440,.08,0,'sine',.055);tone(330,.1,.06,'sine',.045)}else if(kind==='blow'){[659.25,523.25,392,261.63].forEach((f,i)=>tone(f,.18,i*.055,'triangle',.11))}else if(kind==='final'){[392,493.88,587.33,783.99,1046.5].forEach((f,i)=>tone(f,.38,i*.09,'sine',.1))}}
$('#openBtn').onclick=()=>{effect('open');startMusic();celebrate();$('#experience').hidden=false;$('#hero').classList.add('celebrated');$('#musicToggle').hidden=false;setTimeout(()=>document.querySelector('.message').scrollIntoView({behavior:'smooth',block:'start'}),350)};
$('#musicEnable').onclick=()=>{if(playing)stopMusic();else startMusic()};$('#musicToggle').onclick=()=>{if(playing)stopMusic();else startMusic()};
$('#blowBtn').onclick=()=>{effect('blow');const cake=$('#cake');cake.classList.add('off');$('#blowBtn').disabled=true;celebrate();setTimeout(()=>$('#cakeReveal').hidden=false,650)};
$('#oneMore').onclick=()=>{effect('final');$('#final').scrollIntoView({behavior:'smooth',block:'start'})};
$('#replay').onclick=()=>{effect('close');stopMusic();window.scrollTo({top:0,behavior:'smooth'});$('#experience').hidden=true;$('#cake').classList.remove('off');$('#cakeReveal').hidden=true;$('#blowBtn').disabled=false;$('#hero').classList.remove('celebrated');};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal-on-scroll').forEach(e=>observer.observe(e));
data.memories.forEach((m,i)=>{if(m.image){const v=memories.children[i]?.querySelector('.memory-visual');if(v){v.style.backgroundImage=`url('${m.image}')`;v.textContent=''}}});