const data={name:'Akash',date:'September 9, 2026',traits:[['✦','The Energy','Somehow you bring energy into even the most random moments.'],['☀','The Laughs','The best moments usually become funny stories later.'],['◎','The Friendship','The kind of friendship that makes ordinary days better.'],['↗','The Ambition','Keep chasing the things that make you excited about tomorrow.'],['◈','The Vibe','Effortlessly yourself. That is the whole point.'],['✧','The Memories','Here is to making a lot more of them this year.']],memories:[{date:'A day worth keeping',title:'That random day',description:'One of those moments that deserves a place in the album.',image:'./IMG_20250201_170406.jpg'},{date:'Somewhere between plans',title:'The good times',description:'The kind of day that did not need a plan to be memorable.',image:'./IMG_20250101_163830.jpg'},{date:'Still one of the favourites',title:'A moment to remember',description:'A snapshot from a day worth keeping close.',image:'./IMG_20251213_153730.jpg'}],wishes:[['A friend','Keep smiling, keep growing, and keep being the person everyone enjoys having around.'],['Someone who cares','May this year bring you good people, good surprises, and plenty of reasons to laugh.'],['Your future self','You have a lot ahead of you. Go make it a year worth remembering.']]};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),traits=$('#traits'),memories=$('#memories'),wishes=$('#wishes');
function addTap(el,fn){let moved=false,suppressClickUntil=0;el.addEventListener('pointerdown',e=>{moved=false;el._sx=e.clientX;el._sy=e.clientY;try{el.setPointerCapture(e.pointerId)}catch(_){}},{passive:true});el.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-el._sx,e.clientY-el._sy)>10){moved=true;suppressClickUntil=Date.now()+500}},{passive:true});el.addEventListener('pointercancel',()=>{moved=true;suppressClickUntil=Date.now()+500},{passive:true});el.addEventListener('pointerup',e=>{if(moved)suppressClickUntil=Date.now()+500;try{el.releasePointerCapture(e.pointerId)}catch(_){}},{passive:true});el.addEventListener('click',e=>{if(moved||Date.now()<suppressClickUntil){moved=false;return}fn(e)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn(e)}})}
function effect(action){try{if(document.visibilityState==='hidden'||!ensureAudio())return;const sounds={open:[[523.25,.12,0,'sine',.1],[659.25,.12,.08,'sine',.1],[783.99,.2,.16,'sine',.11]],tap:[[783.99,.08,0,'sine',.07],[1046.5,.1,.07,'sine',.06]],wish:[[659.25,.12,0,'triangle',.08],[783.99,.16,.1,'triangle',.08]],blow:[[523.25,.12,0,'sine',.08],[392,.16,.1,'sine',.07],[261.63,.28,.22,'triangle',.06]],final:[[659.25,.16,0,'sine',.08],[783.99,.16,.12,'sine',.08],[1046.5,.3,.24,'sine',.1]],close:[[783.99,.1,0,'sine',.06],[523.25,.2,.09,'sine',.06]]};(sounds[action]||sounds.tap).forEach(([f,d,delay,type,g])=>tone(f,d,delay,type,g))}catch(_) {}}
data.traits.forEach(([icon,title,description])=>{const el=document.createElement('article');el.className='trait';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-expanded','false');el.innerHTML=`<div class="trait-icon">${icon}</div><h3>${title}</h3><p>${description}</p>`;addTap(el,()=>{const open=!el.classList.contains('open');el.classList.toggle('open',open);el.setAttribute('aria-expanded',String(open));effect('tap')});traits.appendChild(el)});
data.memories.forEach((m,i)=>{const el=document.createElement('article');el.className=`memory memory-${i+1}`;el.innerHTML=`<div class="memory-visual" role="img" aria-label="${m.title}" style="background-image:url('${m.image}')"></div><div class="memory-info"><small>${m.date}</small><h3>${m.title}</h3><p>${m.description}</p></div>`;memories.appendChild(el)});
data.wishes.forEach(([from,msg])=>{const el=document.createElement('article');el.className='wish';el.innerHTML=`<p>“${msg}”</p><small>— ${from}</small>`;addTap(el,()=>effect('wish'));wishes.appendChild(el)});
function openModal(m){$('#modalDate').textContent=m.date;$('#modalTitle').textContent=m.title;$('#modalDescription').textContent=m.description;const visual=$('#modalVisual');visual.className='modal-visual';visual.style.backgroundImage=`url('${m.image}')`;visual.textContent='';$('#modal').hidden=false;document.body.style.overflow='hidden';$('#modalClose').focus()}
function closeModal(){effect('close');$('#modal').hidden=true;document.body.style.overflow=''}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()});
function celebrate(){const box=$('#confetti');for(let i=0;i<100;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left='50%';p.style.top='45%';p.style.setProperty('--x',`${(Math.random()-.5)*110}vw`);p.style.setProperty('--y',`${(Math.random()-.3)*110}vh`);p.style.transform=`rotate(${Math.random()*360}deg)`;p.style.background=`hsl(${Math.random()*55+325} 70% ${65+Math.random()*20}%)`;box.appendChild(p)}setTimeout(()=>box.replaceChildren(),2200)}
let audioCtx=null,master=null,compressor=null,playing=false,musicTimer=null;const melody=[523.25,659.25,783.99,1046.5,987.77,783.99,659.25,783.99,880,1046.5,1174.66,1046.5,880,783.99,659.25,783.99,987.77,1046.5,1318.51,1174.66,1046.5,987.77,880,1046.5];
function ensureAudio(){try{if(!audioCtx){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;audioCtx=new Ctx();master=audioCtx.createGain();master.gain.value=.58;compressor=audioCtx.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=10;compressor.ratio.value=4;compressor.attack.value=.003;compressor.release.value=.18;master.connect(compressor);compressor.connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume();return true}catch(_){return false}}
function tone(freq,duration=.3,delay=0,type='sine',gain=.12){if(!ensureAudio())return;const now=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(master);o.start(now);o.stop(now+duration+.025)}
function chord(freqs,delay=0,volume=.045){freqs.forEach((f,i)=>tone(f,.65,delay+i*.018,'triangle',volume))}function playBirthdayPhrase(){for(let i=0;i<melody.length;i++){tone(melody[i],.24,i*.25,'sine',.11);if(i%4===0)tone(melody[i]/2,.48,i*.25,'triangle',.035)}chord([261.63,329.63,392],0,.05);chord([293.66,369.99,440],2.5,.05);chord([329.63,415.3,493.88],5,.05)}
function startMusic(){if(!ensureAudio()||playing)return;playing=true;master.gain.setValueAtTime(.58,audioCtx.currentTime);playBirthdayPhrase();musicTimer=setInterval(()=>{if(playing&&document.visibilityState==='visible')playBirthdayPhrase()},melody.length*250+900);$('#musicToggle').hidden=false;$('#musicToggle').textContent='♫';$('#musicToggle').setAttribute('aria-label','Pause birthday music');$('#musicEnable').textContent='♫ Birthday Music On'}
function stopMusic(){playing=false;clearInterval(musicTimer);musicTimer=null;if(audioCtx){try{master.gain.cancelScheduledValues(audioCtx.currentTime);master.gain.setValueAtTime(0,audioCtx.currentTime);audioCtx.suspend()}catch(_){} }$('#musicToggle').textContent='♪';$('#musicToggle').setAttribute('aria-label','Play birthday music');$('#musicEnable').textContent='♬ Play Birthday Music'}
function handlePageVisibility(){if(document.visibilityState==='hidden')stopMusic()}
document.addEventListener('visibilitychange',handlePageVisibility);window.addEventListener('pagehide',stopMusic);window.addEventListener('beforeunload',stopMusic);
$('#openBtn').onclick=()=>{try{effect('open')}catch(_){};$('#experience').hidden=false;$('#hero').classList.add('celebrated');try{celebrate()}catch(_){};try{startMusic()}catch(_){};$('#musicToggle').hidden=false;setTimeout(()=>{const message=document.querySelector('.message');if(message)message.scrollIntoView({behavior:'smooth',block:'start'})},350)};$('#musicEnable').onclick=()=>{if(playing)stopMusic();else startMusic()};$('#musicToggle').onclick=()=>{if(playing)stopMusic();else startMusic()};$('#blowBtn').onclick=()=>{effect('blow');$('#cake').classList.add('off');$('#blowBtn').disabled=true;celebrate();setTimeout(()=>$('#cakeReveal').hidden=false,650)};$('#oneMore').onclick=()=>{effect('final');$('#final').scrollIntoView({behavior:'smooth',block:'start'})};$('#replay').onclick=()=>{effect('close');stopMusic();window.scrollTo({top:0,behavior:'smooth'});$('#experience').hidden=true;$('#cake').classList.remove('off');$('#cakeReveal').hidden=true;$('#blowBtn').disabled=false;$('#hero').classList.remove('celebrated')};const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal-on-scroll').forEach(e=>observer.observe(e));