const data={name:'Akash',date:'September 9, 2026',traits:[['✦','The Energy','Somehow you bring energy into even the most random moments.'],['☀','The Laughs','The best moments usually become funny stories later.'],['◎','The Friendship','The kind of friendship that makes ordinary days better.'],['↗','The Ambition','Keep chasing the things that make you excited about tomorrow.'],['◈','The Vibe','Effortlessly yourself. That is the whole point.'],['✧','The Memories','Here is to making a lot more of them this year.']],memories:[{date:'A day to remember',title:'That random day',description:"One of those moments we'll always remember.",image:'./IMG_20250101_163830.jpg'},{date:'Somewhere between plans',title:'The good times',description:'The kind of day that did not need a plan.',image:'./IMG_20250201_170406.jpg'},{date:'Still one of the favourites',title:'Another memory',description:'Add a real photo and keep this one forever.',image:'./IMG_20251213_153730.jpg'}],wishes:[['A friend','Keep smiling, keep growing, and keep being the person everyone enjoys having around.'],['Someone who cares','May this year bring you good people, good surprises, and plenty of reasons to laugh.'],['Your future self','You have a lot ahead of you. Go make it a year worth remembering.']]};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),traits=$('#traits'),memories=$('#memories'),wishes=$('#wishes');
function addTap(el,fn){el.addEventListener('click',fn);el.addEventListener('touchend',e=>{if(e.cancelable)e.preventDefault();fn()},{passive:false});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn()}})}
data.traits.forEach(([icon,title,description])=>{const el=document.createElement('article');el.className='trait';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-expanded','false');el.innerHTML=`<div class="trait-icon">${icon}</div><h3>${title}</h3><p>${description}</p>`;addTap(el,()=>{const open=!el.classList.contains('open');el.classList.toggle('open',open);el.setAttribute('aria-expanded',String(open));effect('tap')});traits.appendChild(el)});
data.memories.forEach((m,i)=>{const el=document.createElement('article');el.className=`memory memory-${i+1}`;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',`Open memory ${i+1}`);el.innerHTML=`<div class="memory-visual" style="background-image:url('${m.image}')"></div><div class="memory-info"><small>${m.date}</small><h3>${m.title}</h3><p>${m.description}</p></div>`;addTap(el,()=>{effect('tap');openModal(m)});memories.appendChild(el)});
data.wishes.forEach(([from,msg])=>{const el=document.createElement('article');el.className='wish';el.innerHTML=`<p>“${msg}”</p><small>— ${from}</small>`;addTap(el,()=>effect('tap'));wishes.appendChild(el)});
function openModal(m){$('#modalDate').textContent=m.date;$('#modalTitle').textContent=m.title;$('#modalDescription').textContent=m.description;const visual=$('#modalVisual');visual.className='modal-visual';visual.style.backgroundImage=`url('${m.image}')`;visual.textContent='';$('#modal').hidden=false;document.body.style.overflow='hidden';$('#modalClose').focus()}
function closeModal(){effect('close');$('#modal').hidden=true;document.body.style.overflow=''}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()});
function celebrate(){const box=$('#confetti');for(let i=0;i<100;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left='50%';p.style.top='45%';p.style.setProperty('--x',`${(Math.random()-.5)*110}vw`);p.style.setProperty('--y',`${(Math.random()-.3)*110}vh`);p.style.transform=`rotate(${Math.random()*360}deg)`;p.style.background=`hsl(${Math.random()*55+325} 70% ${65+Math.random()*20}%)`;box.appendChild(p)}setTimeout(()=>box.replaceChildren(),2200)}
let audioCtx=null,master=null,playing=false,musicTimer=null;const melody=[261.63,329.63,392,493.88,523.25,493.88,392,329.63,293.66,349.23,440,523.25,587.33,523.25,440,349.23,392,493.88,587.33,659.25,587.33,493.88,392,329.63];
function ensureAudio(){if(!audioCtx){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;audioCtx=new Ctx();master=audioCtx.createGain();master.gain.value=.46;master.connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume();return true}
function tone(freq,duration=.3,delay=0,type='sine',gain=.12){if(!ensureAudio())return;const now=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(master);o.start(now);o.stop(now+duration+.025)}
function chord(freqs,delay=0){freqs.forEach((f,i)=>tone(f,.5,delay+i*.012,'triangle',.055))}
function playBirthdayPhrase(){for(let i=0;i<melody.length;i++)tone(melody[i],.25,i*.22,'sine',.13);chord([130.81,164.81,196],0);chord([146.83,174.61,220],2.64);chord([164.81,196,246.94],4.84);}
function startMusic(){if(!ensureAudio()||playing)return;playing=true;playBirthdayPhrase();musicTimer=setInterval(()=>{if(playing)playBirthdayPhrase()},melody.length*220+650);$('#musicToggle').hidden=false;$('#musicToggle').textContent='♫';$('#musicToggle').setAttribute('aria-label','Pause birthday music');$('#musicEnable').textContent='♫ Birthday Music On'}
function stopMusic(){playing=false;clearInterval(musicTimer);musicTimer=null;$('#musicToggle').textContent='♪';$('#musicToggle').setAttribute('aria-label','Play birthday music');$('#musicEnable').textContent='♬ Play Birthday Music'}
function effect(kind){if(kind==='open'){chord([523.25,659.25,783.99],0);tone(1046.5,.42,.12,'sine',.16);tone(1318.51,.35,.24,'sine',.12)}else if(kind==='tap'){tone(659.25,.07,0,'sine',.09);tone(987.77,.1,.045,'triangle',.07)}else if(kind==='close'){tone(659.25,.1,0,'sine',.08);tone(523.25,.12,.08,'sine',.065);tone(392,.16,.17,'triangle',.06)}else if(kind==='blow'){for(let i=0;i<9;i++)tone(180+Math.random()*180,.11,i*.035,'sine',.055);[659.25,523.25,392,293.66].forEach((f,i)=>tone(f,.22,i*.08,'triangle',.13))}else if(kind==='final'){chord([392,493.88,587.33],0);chord([440,554.37,659.25],.42);[783.99,987.77,1174.66,1567.98].forEach((f,i)=>tone(f,.45,i*.11,'sine',.14))}}
$('#openBtn').onclick=()=>{effect('open');startMusic();celebrate();$('#experience').hidden=false;$('#hero').classList.add('celebrated');$('#musicToggle').hidden=false;setTimeout(()=>document.querySelector('.message').scrollIntoView({behavior:'smooth',block:'start'}),350)};
$('#musicEnable').onclick=()=>{if(playing)stopMusic();else startMusic()};$('#musicToggle').onclick=()=>{if(playing)stopMusic();else startMusic()};
$('#blowBtn').onclick=()=>{effect('blow');$('#cake').classList.add('off');$('#blowBtn').disabled=true;celebrate();setTimeout(()=>$('#cakeReveal').hidden=false,650)};
$('#oneMore').onclick=()=>{effect('final');$('#final').scrollIntoView({behavior:'smooth',block:'start'})};
$('#replay').onclick=()=>{effect('close');stopMusic();window.scrollTo({top:0,behavior:'smooth'});$('#experience').hidden=true;$('#cake').classList.remove('off');$('#cakeReveal').hidden=true;$('#blowBtn').disabled=false;$('#hero').classList.remove('celebrated')};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal-on-scroll').forEach(e=>observer.observe(e));