import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion';
import { ArrowDown, ArrowLeft, ArrowRight, Camera, Heart, Laugh, MapPin, Music, Pause, Rocket, Sparkles, Star, X } from 'lucide-react';
import { birthdayData as data } from './data';

const iconMap = { sparkles: Sparkles, laugh: Laugh, heart: Heart, rocket: Rocket, star: Star, camera: Camera };

function ParticleBackground({ celebration = false }) {
  const particles = Array.from({ length: celebration ? 44 : 24 }, (_, i) => i);
  return <div className="particle-layer" aria-hidden="true">{particles.map((i) => <span key={i} className={`particle ${celebration ? 'celebrate' : ''}`} style={{ '--i': i, '--x': `${(i * 47) % 100}%`, '--delay': `${(i % 11) * .55}s`, '--size': `${2 + (i % 4)}px` }} />)}</div>;
}

function Reveal({ children, className = '', delay = 0 }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .75, delay, ease: [0.22, 1, .36, 1] }}>{children}</motion.div>;
}

function Hero({ onOpen, musicAvailable, musicEnabled, onMusic }) {
  const [phase, setPhase] = useState(0);
  useEffect(() => { const timers = [setTimeout(() => setPhase(1), 900), setTimeout(() => setPhase(2), 2500), setTimeout(() => setPhase(3), 4200)]; return () => timers.forEach(clearTimeout); }, []);
  return <section className="hero" id="top"><ParticleBackground /><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="hero-content"><motion.div className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .8 }}><span className="eyebrow-dot" /> A little something, made for you</motion.div><div className="hero-copy" aria-live="polite"><AnimatePresence mode="wait"><motion.div key={phase} initial={{ opacity: 0, y: 20, filter: 'blur(8px)' }} animate={{ opacity: 1, y: 0, filter: 'blur(0)' }} exit={{ opacity: 0, y: -20, filter: 'blur(8px)' }} transition={{ duration: .65 }}>{phase === 0 && <h1 className="hero-line">Hey Akash… <span>👀</span></h1>}{phase === 1 && <h1 className="hero-line">Today is <em>not</em> just another day.</h1>}{phase === 2 && <h1 className="hero-line">Because today, someone <em>awesome</em> was born.</h1>}{phase === 3 && <><p className="hero-kicker">September 9, 2026</p><h1 className="hero-title">Happy Birthday,<br /><span>Akash.</span></h1></>}</motion.div></AnimatePresence></div><div className="hero-actions">{phase === 3 && <motion.button className="primary-button" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35 }} onClick={onOpen}>Open Your Birthday Surprise <ArrowRight size={18} /></motion.button>}{musicAvailable && <button className="music-intro" onClick={onMusic}><Music size={15} /> {musicEnabled ? 'Birthday music is on' : 'Enable Birthday Music'}</button>}</div><div className="date-mark"><span>09</span><i>•</i><span>09</span><i>•</i><span>2026</span></div></div><motion.div className="scroll-hint" animate={{ y: [0, 7, 0] }} transition={{ repeat: Infinity, duration: 1.8 }}><ArrowDown size={16} /> scroll when you're ready</motion.div></section>;
}

function BirthdayMessage() { return <section className="section message-section" id="message"><Reveal className="section-heading"><p className="section-label">A note, just because</p><h2>A little something<br /><span>for you…</span></h2></Reveal><Reveal className="message-card" delay={.12}><div className="quote-mark">“</div><p>{data.birthdayMessage}</p><div className="signature">— from someone who is very glad to know you</div></Reveal></section>; }

function Traits() { const [active, setActive] = useState(0); return <section className="section traits-section" id="traits"><Reveal className="section-heading"><p className="section-label">No generic compliments here</p><h2>Things that make<br /><span>Akash… Akash.</span></h2></Reveal><div className="traits-grid">{data.traits.map((trait, i) => { const Icon = iconMap[trait.icon] || Sparkles; return <Reveal key={trait.title} delay={i * .05}><button className={`trait-card ${active === i ? 'active' : ''}`} onClick={() => setActive(i)}><div className="trait-icon"><Icon size={20} /></div><span className="trait-number">0{i + 1}</span><h3>{trait.title}</h3><AnimatePresence initial={false}>{active === i && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}>{trait.description}</motion.p>}</AnimatePresence><ArrowRight className="trait-arrow" size={17} /></button></Reveal>; })}</div></section>; }

function Memories() { const [selected, setSelected] = useState(null); const [index, setIndex] = useState(0); const next = () => setIndex((index + 1) % data.memories.length), prev = () => setIndex((index - 1 + data.memories.length) % data.memories.length); return <section className="section memories-section" id="memories"><Reveal className="section-heading split"><div><p className="section-label">The good stuff</p><h2>Our <span>moments.</span></h2></div><p className="section-note">Real memories can live here.<br />Just add photos to <code>/public/images/</code>.</p></Reveal><div className="memory-stage">{data.memories.map((memory, i) => <motion.button key={memory.title} className={`memory-card memory-${i} ${i === index ? 'current' : ''}`} onClick={() => setSelected(memory)} animate={{ opacity: i === index ? 1 : .38, scale: i === index ? 1 : .94, x: `${(i - index) * 7}%`, rotate: (i - index) * 2 }} transition={{ duration: .55 }}><div className="memory-image"><img src={memory.image} alt="" loading="lazy" onError={(e) => { e.currentTarget.style.display = 'none'; e.currentTarget.parentElement.classList.add('placeholder'); }} /><div className="placeholder-content"><Camera size={25} /><span>Photo goes here</span><small>Add {`memory-${i + 1}.jpg`}</small></div></div><div className="memory-meta"><span>{memory.date}</span><h3>{memory.title}</h3><p>{memory.description}</p></div></motion.button>)}</div><div className="gallery-controls"><button onClick={prev} aria-label="Previous memory"><ArrowLeft size={18} /></button><span>{String(index + 1).padStart(2, '0')} / {String(data.memories.length).padStart(2, '0')}</span><button onClick={next} aria-label="Next memory"><ArrowRight size={18} /></button></div><AnimatePresence>{selected && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div className="memory-modal" initial={{ opacity: 0, scale: .94, y: 18 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .94 }} onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}><X size={19} /></button><div className="modal-visual"><img src={selected.image} alt="" onError={(e) => { e.currentTarget.style.display = 'none'; }} /><Camera size={34} /></div><div><span className="section-label">{selected.date}</span><h3>{selected.title}</h3><p>{selected.description}</p></div></motion.div></motion.div>}</AnimatePresence></section>; }

function Wishes() { const [active, setActive] = useState(0); return <section className="section wishes-section" id="wishes"><Reveal className="section-heading"><p className="section-label">A few words from the people who care</p><h2>Messages <span>for you.</span></h2></Reveal><div className="wishes-wrap"><div className="wish-progress"><span style={{ width: `${((active + 1) / data.wishes.length) * 100}%` }} /></div><AnimatePresence mode="wait"><motion.article key={active} className="wish-card" initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }} transition={{ duration: .4 }}><Heart className="wish-heart" size={22} fill="currentColor" /><blockquote>“{data.wishes[active].message}”</blockquote><div className="wish-author"><strong>{data.wishes[active].name}</strong><span>{data.wishes[active].relationship}</span></div></motion.article></AnimatePresence><div className="wish-controls"><button onClick={() => setActive((active - 1 + data.wishes.length) % data.wishes.length)}><ArrowLeft size={17} /></button><div>{data.wishes.map((_, i) => <button key={i} className={i === active ? 'active' : ''} onClick={() => setActive(i)} aria-label={`Wish ${i + 1}`} />)}</div><button onClick={() => setActive((active + 1) % data.wishes.length)}><ArrowRight size={17} /></button></div></div></section>; }

function Confetti({ fire }) { const bits = Array.from({ length: 70 }, (_, i) => i); return fire ? <div className="confetti" aria-hidden="true">{bits.map(i => <i key={i} style={{ '--i': i, '--left': `${(i * 37) % 100}%`, '--delay': `${(i % 13) * .025}s`, '--rotate': `${(i * 47) % 360}deg` }} />)}</div> : null; }

function BirthdayCake({ onFinal }) { const [blown, setBlown] = useState(false); const [fire, setFire] = useState(false); const blow = () => { if (blown) return; setBlown(true); setFire(true); setTimeout(() => setFire(false), 2600); }; return <section className="section cake-section" id="cake"><ParticleBackground celebration={fire} /><Reveal className="cake-copy"><p className="section-label">The important part</p><h2>Okay…<br /><span>make a wish.</span></h2><p>Close your eyes for a second. Think of something you really want this year.</p></Reveal><Reveal className="cake-scene" delay={.15}><div className={`cake ${blown ? 'blown' : ''}`}><div className="candles">{[0,1,2,3,4].map(i => <span key={i} style={{ '--c': i }}><b className="flame" /></span>)}</div><div className="cake-top" /><div className="cake-body"><i /><i /><i /></div><div className="cake-base" /></div><AnimatePresence mode="wait">{!blown ? <motion.button key="blow" className="primary-button cake-button" onClick={blow}>Blow the candles <Sparkles size={17} /></motion.button> : <motion.div key="revealed" className="wish-reveal" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}><p>May this year be your <em>best chapter yet.</em></p><button className="ghost-button" onClick={onFinal}>There’s one more thing <ArrowRight size={17} /></button></motion.div>}</AnimatePresence></Reveal><Confetti fire={fire} /></section>; }

function FinalSurprise({ onReplay }) { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] }); const y = useTransform(scrollYProgress, [0, 1], ['-8%', '8%']); return <section ref={ref} className="final-section" id="final"><motion.div className="final-stars" style={{ y }} /><ParticleBackground celebration /><div className="final-content"><Reveal><p className="section-label">One last thing, Akash…</p><h2>{data.finalMessage.split('\n')[0]}</h2><div className="final-body">{data.finalMessage.split('\n').slice(1).map((line, i) => line ? <p key={i} className={line.includes('beautiful') || line.includes('Happy') ? 'final-emphasis' : ''}>{line}</p> : <span key={i} className="final-space" />)}</div><div className="final-date">09.09.2026</div><button className="replay-button" onClick={onReplay}><ArrowLeft size={16} /> Experience it again</button></Reveal></div></section>; }

function MusicToggle({ audio, enabled, onToggle }) { if (!audio) return null; return <button className="music-toggle" onClick={onToggle} aria-label={enabled ? 'Pause music' : 'Play music'}>{enabled ? <Pause size={16} /> : <Music size={16} />}</button>; }

export default function App() { const [opened, setOpened] = useState(false), [final, setFinal] = useState(false), [musicEnabled, setMusicEnabled] = useState(false), [celebrate, setCelebrate] = useState(false); const audioRef = useRef(null); const [musicAvailable, setMusicAvailable] = useState(true); useEffect(() => { const audio = audioRef.current; const onError = () => setMusicAvailable(false); audio?.addEventListener('error', onError); return () => audio?.removeEventListener('error', onError); }, []); const toggleMusic = () => { const audio = audioRef.current; if (!audio || !musicAvailable) return; if (musicEnabled) { audio.pause(); setMusicEnabled(false); } else { audio.play().then(() => setMusicEnabled(true)).catch(() => setMusicEnabled(false)); } }; const open = () => { setOpened(true); setCelebrate(true); setTimeout(() => setCelebrate(false), 2200); setTimeout(() => document.getElementById('message')?.scrollIntoView({ behavior: 'smooth' }), 250); }; const replay = () => { setFinal(false); setOpened(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }; return <div className="app"><audio ref={audioRef} src="./audio/birthday.mp3" loop preload="none" /><AnimatePresence>{!opened && <Hero onOpen={open} musicAvailable={musicAvailable} musicEnabled={musicEnabled} onMusic={toggleMusic} />}</AnimatePresence>{opened && !final && <main><BirthdayMessage /><Traits /><Memories /><Wishes /><BirthdayCake onFinal={() => { setFinal(true); setTimeout(() => document.getElementById('final')?.scrollIntoView({ behavior: 'smooth' }), 100); }} /></main>}{final && <FinalSurprise onReplay={replay} />}<MusicToggle audio={musicAvailable} enabled={musicEnabled} onToggle={toggleMusic} />{celebrate && <Confetti fire={celebrate} />}</div>; }
